export const GET_CHARACTERS = "GET_CHARACTERS";
export const GET_CHARACTER = "GET_CHARACTER";
export const GET_CHARACTER_EPISODES = "GET_CHARACTER_EPISODES";
export const CLEAN_CHARACTER = "CLEAN_CHARACTER";
export const SET_IS_SEARCHING = "SET_IS_SEARCHING";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_ERROR = "SET_ERROR";
export const SET_LOADING = "SET_LOADING";
